public with sharing class ServiceToTest {
	public ServiceToTest() {

	}

	public static void ordering(Set<Id> opportunityId)
	{
		//load opportunities

		//load oppLines

		//load contacts

		//create email for contacts and update

		//save contacts
	}

	public static void answer(Set<Id> opportunityId)
	{
		//load opportunities

		//load oppLines

		//load contacts

		//create email for contacts and update

		//save contacts
	}

	public static void capture(Set<Id> opportunityId)
	{
		//load opportunities

		//load oppLines

		//load contacts

		//create email for contacts and update

		//save contacts
	}
}